### ISSUE TITLE
1.13.1 update?

### ISSUE THREAD

**Issue by RustyDagger** [BONNe/EasierVillagerTrading#1]
Hi, I must say I love this mod, However I am playing on minecraft 1.13.1 
Are there any plans to update?

**Comment by BONNe** [comment]
I would also like to use this mod in 1.13.1 but Forge is not updated yet.

But writing mod without forge would be pain in ass...

I will update it as soon as Forge will come out.

**Comment by RustyDagger** [comment]
I'm confused what do you mean comes out. 
https://www.minecraft-downloads.com/minecraft-forge-mod-for-windows-and-mac/

**Comment by BONNe** [comment]
Not sure about a link that you provide. As much as I know, Forge is not updated to 1.13 yet and MinecraftForge team is still working on a pre-release version. 
Also, the official Minecraft forge webpage is:
https://files.minecraftforge.net/
Downloading forge from other links can potentially harm your computer.

**Comment by BONNe** [comment]
I updated to 1.13.2 version.

Unfortunately config editing is available only via config file, as Forge Config Editing Gui is not implemented yet.

Works with latest Forge Build.
